#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

pluginname=$(basename $0 .sh)

if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from FHEM Plugin"
fi

# Set correct permissions on older LoxBerry systems prior 0.3.x
if [ $EUID -eq 0 ]; then
	/usr/sbin/usermod -aG dialout loxberry > /dev/null 2>&1
	/usr/sbin/usermod -aG tty loxberry > /dev/null 2>&1
fi

is_running() {
	/bin/ps -C "perl fhem.pl" -opid= > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
    	PID=`/bin/ps -C "perl fhem.pl" -opid=`
        echo "Fhem is already running. PID: $PID"
    else
        echo "Starting Fhem..."
	if [ $EUID -eq 0 ]; then
		su loxberry -c "cd REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME && /usr/bin/perl fhem.pl REPLACEINSTALLFOLDER/config/plugins/REPLACEFOLDERNAME/fhem.cfg"
	else
		cd REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME
		/usr/bin/perl fhem.pl REPLACEINSTALLFOLDER/config/plugins/REPLACEFOLDERNAME/fhem.cfg
	fi
        if ! is_running; then
            echo "Unable to start Fhem."
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
    	PID=`/bin/ps -C "perl fhem.pl" -opid=`
        echo -n "Stopping Fhem..."
        kill $PID 
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Fhem could not be stopped; may still be shuting down or shutdown may have failed."
            exit 1
        else
            echo "Fhem is stopped."
        fi
    else
        echo "Fhem is not running."
    fi
    ;;
    restart)
    /bin/sh $0 stop
    if is_running; then
p
        echo "Unable to stop Fhem, will not try to restart."
        exit 1
    fi
    /bin/sh $0 start
    ;;
    status)
    if is_running; then
    	PID=`/bin/ps -C "perl fhem.pl" -opid=`
        echo "Fhem is running. PID: $PID"
    else
        echo "Fhem is stopped."
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    echo "No command given, assuming start."
    /bin/bash $0 start
    ;;
esac

exit 0
